import type { Metadata } from 'next'
import TopMenu from '@/components/TopMenu'


export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function Layout({ children }: { children: React.ReactNode }) {

    return (
        <>
            <TopMenu />
            {children}
        </>
    )
}
